[luacov-reporter-lcov]
fetch.github = "daurnimator/luacov-reporter-lcov"
src.git = "https://github.com/daurnimator/luacov-reporter-lcov"
src.branch = "master"

[mini-test]
fetch.github = "nvim-mini/mini.test"
src.git = "https://github.com/nvim-mini/mini.test"
src.branch = "main"

[nvim-treesitter]
fetch.github = "nvim-treesitter/nvim-treesitter"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"
src.branch = "main"
