# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  luacov-reporter-lcov = {
    pname = "luacov-reporter-lcov";
    version = "4d881ddb4eeec5ac0cd7d4b7679e3e59f9ac5745";
    src = fetchFromGitHub {
      owner = "daurnimator";
      repo = "luacov-reporter-lcov";
      rev = "4d881ddb4eeec5ac0cd7d4b7679e3e59f9ac5745";
      fetchSubmodules = false;
      sha256 = "sha256-o+9E+pMVpWpd4M0gBnU0g9OA7UZjNbuqFa6WG2j73nE=";
    };
    date = "2019-11-01";
  };
  mini-nvim = {
    pname = "mini-nvim";
    version = "9d359222b3643f1fccbd8f3180445842e1cae00b";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.nvim";
      rev = "9d359222b3643f1fccbd8f3180445842e1cae00b";
      fetchSubmodules = false;
      sha256 = "sha256-uZ4KXLw/0hN/0nY16Oh1zzI5gBSyX5+lcx7frECHT/w=";
    };
    date = "2026-03-09";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "5cb05e1b0fa3c469958a2b26f36b3fe930af221c";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "5cb05e1b0fa3c469958a2b26f36b3fe930af221c";
      fetchSubmodules = false;
      sha256 = "sha256-C2LcXM+J+1aJ0RGsIXpRRkWbeqRN00kWWhfkyBqgY2M=";
    };
    date = "2026-03-07";
  };
}
