# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "d660b7c002f3922b6bb3da47206645488a698426";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "d660b7c002f3922b6bb3da47206645488a698426";
      fetchSubmodules = false;
      sha256 = "sha256-Br313yAD17I3D+DX5PYY2b6r5IvmnXk//ak+wtB43m8=";
    };
    date = "2026-02-23";
  };
}
